spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/theater_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: 6379
    cache:
      type: redis
      redis:time-to-live: 10m

api:
  reservation:
    url: ${RESERVATION_SERVICE_URL:http://localhost:8083}

server:
  port: 8082

jwt:
  secret: ${JWT_SECRET}